### ISSUE TITLE
System drop list not reset after lock system

### ISSUE THREAD

**Issue by Blackout76** [pfh59/eve-whmapper#140]
Lock a system by right click on a system and click "Lock"
Try open again the system menu by right click on the same system.
It doesn't work!

U must reset the cursor by clicking somewhere else (backaground for example) to reset the cursor
Only after this step, u can open the system menu again

**Comment by Blackout76** [comment]
The menu disapear only after 2 left click somewhere else. 
A simple left or right click on other system not allow to close the previous menu and select the new system (menu or not)

**Comment by pfh59** [comment]
will be fixed in next patch
