### ISSUE TITLE
Add connection marker start<>end

### ISSUE THREAD

**Issue by Blackout76** [pfh59/eve-whmapper#143]
The following case show 4 systems that should be connected:
![image](https://github.com/pfh59/eve-whmapper/assets/13513034/bdf94bf0-c9b5-4a28-ba87-f2d8f54c852a)

If i move the system at the middle at the bottom, we have the following result:
![image](https://github.com/pfh59/eve-whmapper/assets/13513034/8a2ee272-45c2-434c-8ad4-f19267cf9ec6)

It would be nice to have a market indicator to show the connection start<>end
![image](https://github.com/pfh59/eve-whmapper/assets/13513034/2c983a0a-0235-4808-b733-f46eb5f65249)

And/Or connections selected system in other color like this:
![image](https://github.com/pfh59/eve-whmapper/assets/13513034/b21971f9-01b7-41e9-9610-2d4d58bf8e32)

**Comment by pfh59** [comment]
change to feature , it's not a bug

**Comment by rdymade** [comment]
That looking fine to you?
![image](https://github.com/pfh59/eve-whmapper/assets/6643263/3f2fd9a5-a375-4d3a-92bd-4457a49f58a6)
