### ISSUE TITLE
Multi Character Tracking in one page

### ISSUE THREAD

**Issue by rdymade** [pfh59/eve-whmapper#180]
Type: Feature
Priority: Nice to have

Content:
- Make it possible to have multiple characters linked in one browser page
- Create the possibility to turn tracking for single already linked characters on/off

**Comment by pfh59** [comment]
i will check, but for me is not possible to have multi account in same page.
Each account have a specific bearer token sended by CCP after logging and store inside your web session during x minute before expiration and renewal.
That why I need to open new tab or page for each characters

**Comment by rdymade** [comment]
hm was just an idea which i always thought would be nice to have but if its hard/almost impossible to implement then probably close this

**Comment by rdymade** [comment]
too complex to implement closed for now
