### ISSUE TITLE
Routing Module

### ISSUE THREAD

**Issue by rdymade** [pfh59/eve-whmapper#182]
Type: Feature
Priority: Mandatory for me to use it in production :)

Requirements:
- Users should be able to define a list of target systems for which the shortest route gets calculated from the selected system
- Should also include thera connections
- easy way to set systems as destionations from the calculated routes
- routes should be shown in a new view maybe make it able to turn this view on and off

**Comment by pfh59** [comment]
I agree with that. This will be my next feature project 😄

**Comment by rdymade** [comment]
Would make sense to use the eve-scout api for this as it also already supports turnur.

**Comment by pfh59** [comment]
It's a possibility, but I'd rather have my own system than a third-party one. If I have no choice eve-scout API is a good option

**Comment by pfh59** [comment]
see #194

**Comment by rdymade** [comment]
will be implemented with #194

**Comment by pfh59** [comment]
feature done
