### ISSUE TITLE
Show SystemLink Age

### ISSUE THREAD

**Issue by rdymade** [pfh59/eve-whmapper#183]
Type: Feature
Priority: Nice To Have

Requirements:
- show for how long a connection was already up
- show for how long a connection was marked as EOL
- this can be at the press of a button to turn it on/off

**Comment by pfh59** [comment]
About how long a connection was already up : you have already this infos in signature modules but not EOL infos

I can add a tooltip when the link is selected and the mouse hovered over it to display both pieces of information.

**Comment by rdymade** [comment]
Sometimes (especially if its long chain's) people don't paste signatures. Would this be a big issue to track when a link was created and use that time for the tooltip?

Also Pathfinder has this little plane thing when you hover over it it shows the age of all links
![image](https://github.com/pfh59/eve-whmapper/assets/6643263/175c19cf-4471-4601-a0a4-2eca5ed30b05)

i always found that issue really usefull especially with multi timezone corporations/alliances

**Comment by pfh59** [comment]
i understand the you, I add a tooltip when the link is selected and the mouse hovered over it to display both pieces of information.

**Comment by rdymade** [comment]
Sounds good to me if you wan't i can start development on this.

**Comment by rdymade** [comment]
Sorry for the delay but was really busy IRL i started work on this yesterday.

One thing i noticed is that mudblazor does not support tooltips on links (at least i found nothing in the documentation)
@pfh59 do you have an idea on how i could go about this? one idea i had is to use the LinkLabel for it and in addition to showing the SystemLinkSize display the first jump time when the link is selected. Would this be an acceptable solution for you?

**Comment by pfh59** [comment]
@rdymade , I try tonight another package to magne context menu on Blazor page

**Comment by pfh59** [comment]
@rdymade , i already explored to use LinkLabel but the result was to bad.
I display info on cards when link is selected
![image](https://github.com/pfh59/eve-whmapper/assets/109206285/e93cfa18-3bce-47fd-9a15-a3abe22ebb53)

But if you have another idea, go

**Comment by rdymade** [comment]
displaying the link age in the card should be good enough will close for now until ppl complain i guess :)
