### ISSUE TITLE
Jump tracking for connections

### ISSUE THREAD

**Issue by rdymade** [pfh59/eve-whmapper#184]
Type: Feature
Priority: Normal

Requirements:
- log all jumps through a connection (datetime/Pilot/Ship/mass) (mandatory)
- possibility to define custom masses for ships (nice to have)

**Comment by pfh59** [comment]
shipped since yesterday evening : commit https://github.com/pfh59/eve-whmapper/commit/20f14fc0522a060ea403d98eff8fd3b1ef95be11

Some updates are incomming

**Comment by pfh59** [comment]
- see #231
