### ISSUE TITLE
System Status bug

### ISSUE THREAD

**Issue by pfh59** [pfh59/eve-whmapper#186]
**Describe the bug**
After setting or changing system status, the menu stay opened. To close it, you need to click two times in brower

**To Reproduce**
1. Select Node System
2. Set or Change System Status
3. Menu still open

**Expected behavior**
Menu must be close

**Screenshots**
![image](https://github.com/pfh59/eve-whmapper/assets/109206285/100024ee-f83e-49c0-af19-7dbefa6e140f)

**Desktop (please complete the following information):**
 - OS: [OS Sonoma]
 - Browser [Safari]

**Additional context**

**Comment by rdymade** [comment]
the issue with it staying open was already there before was not able to find the source easily.

like you also need to double click when only right clicking without selecting any of the menu options.

**Comment by pfh59** [comment]
don't worry, I know this issue. I try to fix it tonight
