### ISSUE TITLE
Submenu open, click doesnt taking in account in many cases

### ISSUE THREAD

**Issue by Blackout76** [pfh59/eve-whmapper#214]
if u open a submenu (system or connection), u will only able to left clic in the map somewhere there is nothing OR u can also zoom in/out

but u cant:
- left click on other system
- right click for opening submenu (system or connection)
- move map
- move system
- maybe more actions ...

**Comment by pfh59** [comment]
bug open : https://github.com/MudBlazor/MudBlazor/issues/8124

**Comment by pfh59** [comment]
use another lib
