### ISSUE TITLE
Routing gets wrong amounts of jumps from ESI

### ISSUE THREAD

**Issue by rdymade** [pfh59/eve-whmapper#216]
**Describe the bug**
Routing is not working as expected.

**To Reproduce**
Route between Amarr and Jita is shown as 24 jumps which should be 11
To me it looks like the Routes endpoint from CCP is simple giving wrong results...

**Expected behavior**
Two possible solutions:
Implement our own routing calculation based on the SDE (and maybe thera/turnur connections in the future)
Rely on external services for routing like eve-scout

**Screenshots**
23 Jumps shown
![image](https://github.com/pfh59/eve-whmapper/assets/6643263/82786b18-5147-4c37-9c90-3a720f21ae46)
11 jumps ingame
![image](https://github.com/pfh59/eve-whmapper/assets/6643263/ec726ff7-7c2a-4c89-8af5-e65f25756b52)

**Comment by pfh59** [comment]
indeed, I will check

**Comment by pfh59** [comment]
The ESI API is not up to date. It's very annoying, you wonder why CCP cares about the API if it doesn't maintain it...

fix : in progress

**Comment by pfh59** [comment]
Bug open to CCP : https://github.com/esi/esi-issues/issues/1371

Dev is ok, it will be pushed sooner after a short refactoring.
