### ISSUE TITLE
Change wh connection status name

### ISSUE THREAD

**Issue by Blackout76** [pfh59/eve-whmapper#229]
Current:
![image](https://github.com/pfh59/eve-whmapper/assets/13513034/110b743b-339c-4eab-84c4-7c9079e152d6)

but critical and verge is same in eve online. (confusion)

You should put something like:
- Normal
- Massed
- Critical or Verge

**Comment by pfh59** [comment]
WH description status is :
- This wormhole has not yet had its stability significantly disrupted by ships passing through it => Normal
- This wormhole has had its stability reduced by ships passing through it, but not to a **critical** degree yet => Critical
- This wormhole has had its stability critically disrupted by the mass of numerous ships passing through and is on the **verge** of collapse => Verge
