### ISSUE TITLE
Remove built-in networking 

### ISSUE THREAD

**Issue by WillusMollusc** [pfh59/eve-whmapper#243]
Most of us already have preconfigured networking and other services on our servers.

Would it be possible to simplify the built in proxy and cert generation to make it easier for those of us who do?

A simple nginx container configured appropriately would normally be sufficient.

Perhaps this could be done with optional containers, which can be commented out as needed?

**Comment by pfh59** [comment]
Hi,

Would you like to use it on docker or as standalone package?

On docker you can use this  [docker-compose.yml] (https://github.com/pfh59/eve-whmapper/blob/main/docker/eve-whmapper/docker-compose.yml)

See bellow the config file with **ports** command to expose whmapper on your network in port 80

> version: '3.5'
> 
> services:
>   db:
>     image: postgres:15-alpine
>     restart: always
>     environment:
>       POSTGRES_USER: ${POSTGRES_USER:-postgres}
>       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
>       POSTGRES_DB: whmapper
>       PGDATA: /data/postgres
>     volumes:
>      - postgres:/data/postgres
>     networks:
>      - net
> 
>   redis:
>     image: redis:7-alpine
>     restart: always
>     networks:
>      - net
> 
>   whmapper:
>     image: ghcr.io/pfh59/eve-whmapper:1.0 #Release version change to latest to have all version
**>     ports :**
**>         - "80:8080"** 
>     restart: unless-stopped
>     environment:
>      - EveSSO__ClientId=xxxxxxxxx
>      - EveSSO__Secret=xxxxxxxxx
>      - ConnectionStrings__DatabaseConnection=server=db;port=5432;database=whmapper;User Id=postgres;Password=secret
>      - ConnectionStrings__RedisConnection=redis:6379
>      - Logging__LogLevel__Default=Warning
>      - Logging__LogLevel__Microsoft.EntityFrameworkCore.Database.Command=Warning
>     links:
>       - db     
>     depends_on:
>       - db 
>     networks:
>      - net
> 
> networks:
>   net:
> 
> volumes:
>     postgres:

Other way is to download linux or windows artifacts and run it as standalone package.

**Comment by WillusMollusc** [comment]
That works perfectly, thanks so much.
