### ISSUE TITLE
Tracking not working when tab is not focused

### ISSUE THREAD

**Issue by rdymade** [pfh59/eve-whmapper#263]
**Describe the bug**
Tracking does not work when the browser tab where whmapper is running is not focused.

**To Reproduce**
1. Open whmapper
2. Open google.com on a second tab and keep it open
3. jump multiple systems (a chain)
4. Open the whmapper tab again
5. Find that the inbetween wormholes have not been tracked

**Expected behavior**
Tracking for wormholes should also work when the browser tab is not focused

**Comment by pfh59** [comment]
hi @rdymade ,

i have no issue but two possibilities :

### First way

If you are using the latest main version not from fresh install, database update have an issue about  3 columns on table JumplLogs. To fix it , entering into your posgres container and run this command :
```
alter table "JumpLogs" alter column "ShipMass" drop not null ;
alter table "JumpLogs" alter column "ShipItemId" drop not null;
alter table "JumpLogs" alter column "ShipTypeId" drop not null;
```

###Second way

SignalR connection timeouts if browser tab is inactive, I'm working on it.
SignalR is used for real time sync with other player connected on the same whmapper server

**Comment by pfh59** [comment]
i refactor db migration in next build

**Comment by rdymade** [comment]
i tested the steps you outlined it works now so i think it was an issue with me running the main branch with the broken db migration

**Comment by rdymade** [comment]
it happened again :)
this is what it looks like (screenshot of what it should look like below)
![image](https://github.com/pfh59/eve-whmapper/assets/6643263/3e7ebc57-ec98-43ad-a54d-3f1480acaee3)

this is what it should look like:
![image](https://github.com/pfh59/eve-whmapper/assets/6643263/b8296dda-f08d-4eaa-a0c8-8da918c177ef)

**Comment by pfh59** [comment]
hi @rdymade ,
is it only happen when your not focus on whmappet tabs?
Do you use chrome or Firefox?

**Comment by rdymade** [comment]
i've only seen it happening when tab is not focused.
i'm using Opera GX (chromium)

here's the relevant logs:
`whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       AddSystemNode Error
whmapper_1  |       System.NullReferenceException: Object reference not set to an instance of an object.
whmapper_1  |          at WHMapper.Pages.Mapper.Overview.AddSystemNode(WHMap map, ESISolarSystem src, ESISolarSystem target) in /src/Pages/Mapper/Overview.cs:line 1252
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       Add System Node error
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       CreateLink src or target node is null
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       Add Wormhole Link error
whmapper_1  | warn: WHMapper.EveMapperRoutePlannerHelper[0]
whmapper_1  |       No connection from solar system 31001611
whmapper_1  | warn: WHMapper.EveMapperRoutePlannerHelper[0]
whmapper_1  |       No connection from solar system 31001611
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       AddSystemNode Error
whmapper_1  |       System.NullReferenceException: Object reference not set to an instance of an object.
whmapper_1  |          at WHMapper.Pages.Mapper.Overview.AddSystemNode(WHMap map, ESISolarSystem src, ESISolarSystem target) in /src/Pages/Mapper/Overview.cs:line 1252
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       Add System Node error
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       CreateLink src or target node is null
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       Add Wormhole Link error
whmapper_1  | warn: WHMapper.EveMapperRoutePlannerHelper[0]
whmapper_1  |       No connection from solar system 31001637
whmapper_1  | warn: WHMapper.EveMapperRoutePlannerHelper[0]
whmapper_1  |       No connection from solar system 31001637
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       AddSystemNode Error
whmapper_1  |       System.NullReferenceException: Object reference not set to an instance of an object.
whmapper_1  |          at WHMapper.Pages.Mapper.Overview.AddSystemNode(WHMap map, ESISolarSystem src, ESISolarSystem target) in /src/Pages/Mapper/Overview.cs:line 1252
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       Add System Node error
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       CreateLink src or target node is null
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       Add Wormhole Link error
whmapper_1  | warn: WHMapper.EveMapperRoutePlannerHelper[0]
whmapper_1  |       No connection from solar system 31002333
whmapper_1  | warn: WHMapper.EveMapperRoutePlannerHelper[0]
whmapper_1  |       No connection from solar system 31002333
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       AddSystemNode Error
whmapper_1  |       System.NullReferenceException: Object reference not set to an instance of an object.
whmapper_1  |          at WHMapper.Pages.Mapper.Overview.AddSystemNode(WHMap map, ESISolarSystem src, ESISolarSystem target) in /src/Pages/Mapper/Overview.cs:line 1252
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       Add System Node error
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       CreateLink src or target node is null
whmapper_1  | fail: WHMapper.Pages.Mapper.Overview[0]
whmapper_1  |       Add Wormhole Link error
`

**Comment by rdymade** [comment]
I'm somewhat certain it has something to do with me using Opera GX.
I'm not able to reproduce the bug in any way while using Firefox.

**Comment by pfh59** [comment]
@rdymade, do you reproduce the issue since commit  https://github.com/pfh59/eve-whmapper/commit/ac70b3e2df6fba3a5c8be26e282eefc47c3228eb
