### ISSUE TITLE
SDE not loading

### ISSUE THREAD

**Issue by pfh59** [pfh59/eve-whmapper#276]
**Describe the bug**
SDE not loading since new update equinox.

**Comment by rysiuwroc** [comment]
I literally burnt +5h today on this #275 here 😅

**Comment by pfh59** [comment]
Zip archive is changed

**Comment by pfh59** [comment]
sorry can't see, your issue.
It"s fix in 2 minutes, commit in progress

**Comment by pfh59** [comment]
same as #275

**Comment by rysiuwroc** [comment]
thank you <3
