### ISSUE TITLE
Can't search for some Character Names

### ISSUE THREAD

**Issue by etchesou** [pfh59/eve-whmapper#325]
**Describe the bug**
I'm trying to add a char to the WHMapper Entities Access. The Name of the Char is something like this: "Name To"

This Character just never shows up under search, doesn't matter what I'm trying. Names like "blaNamebla blaTo" or other names which include Parts of the Name show up, just not the specific Character I want to add.

Is there anything I could try? Can you manually add names to the DB or something?

**Expected behavior**
Should be able to search for and add any Character.

**Comment by pfh59** [comment]
hi @etchesou , 

What kind of version are you using?

Manual Workaround : 

You can add manually the user inside de table whaccess.  Y
You need to set : 
- EveEntityId : it's the character id (you can find it in zkillboard : https://zkillboard.com/character/**1222401549**/)
- EveEntityName : the name of the character
- EveEntity : 1 (for Character)

**Comment by etchesou** [comment]
I'm using the latest version, 1.1.2.

The actual name I want to add is: Ryan Ry (if this info helps)

**Comment by etchesou** [comment]
managed to add the Character manually, but still strange that it does not work "the normal way"

**Comment by pfh59** [comment]
I reproduce the issue with the character 'Ryan Ry'.
I will investigate this issue.

**Comment by pfh59** [comment]
v1.1.3 include the fix

**Comment by etchesou** [comment]
Sweet, that was quick! Thanks you very much!
